ginsberg_transportation:
  resource: "@GinsbergTransportationBundle/Controller"
  type: annotation
  prefix: /
login:
  path: /login
  defaults: { _controller: "GinsbergTransportationBundle:Security:login" }
login_check:
  path: /login_check