ginsberg_transportation:
  resource: "@GinsbergTransportationBundle/Controller/"
  type: annotation
  prefix: /
ginsberg_transportation_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: GinsbergTransportationBundle:Default:index }
site:
  pattern: /site
  defaults: { _controller: "GinsbergTransportationBundle:Default:index" }
login:
  path: /login
  defaults: { _controller: "GinsbergTransportationBundle:Security:login" }
login_check:
  path: /login_check