parameters:
    ginsberg_transportation.user.class: Ginsberg\TransportationBundle\DependencyInjection\User

services:
    user:
        class: %ginsberg_transportation.user.class%
    ginsberg_transportation.form.type.person:
      class: Ginsberg\TransportationBundle\Form\Type\PersonType
      tags:
        - { name: form.type, alias: person }
