parameters:
    ginsberg_transportation.user.class: Ginsberg\TransportationBundle\DependencyInjection\User

services:
    user:
        class: %ginsberg_transportation.user.class%
#        arguments: [@service_id, "plain_value", %parameter%]
