parameters:
  ginsberg_transportation.user.class: Ginsberg\TransportationBundle\Services\User
  ginsberg_transportation.res_utils.class: Ginsberg\TransportationBundle\Services\ReservationUtils
  ginsberg_transportation.program_service.class: Ginsberg\TransportationBundle\Services\ProgramService
  ginsberg_transportation.person_service.class: Ginsberg\TransportationBundle\Services\PersonService
  ginsberg_transportation.installation_service.class: Ginsberg\TransportationBundle\Services\InstallationService
  user_provider.class: Ginsberg\TransportationBundle\Security\User\UserProvider
    
services:
  ginsberg_user:
    class: "%ginsberg_transportation.user.class%"
  user_provider:
    class: "%user_provider.class%"
    arguments:
      ["@ginsberg_person.person_repository", "@person_service", "@logger"]
  res_utils: 
    class: %ginsberg_transportation.res_utils.class%
    arguments: ["@request_stack"]
  program_service:
    class: %ginsberg_transportation.program_service.class%
    arguments: 
      ["@ginsberg_program.program_repository", "@logger"]
  person_service:
    class: %ginsberg_transportation.person_service.class%
    arguments: 
      ["@ginsberg_person.person_repository", "@logger"]
  installation_service:
    class: %ginsberg_transportation.installation_service.class%
    arguments:
      ["@ginsberg_installation.installation_repository", "@logger"]
  ginsberg_transportation.form.type.person:
    class: Ginsberg\TransportationBundle\Form\Type\PersonType
    tags:
      - { name: form.type, alias: person }
  ginsberg_person.person_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - Ginsberg\TransportationBundle\Entity\Person
  ginsberg_program.program_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - Ginsberg\TransportationBundle\Entity\Program
  ginsberg_installation.installation_repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - Ginsberg\TransportationBundle\Entity\Installation
  validator.unique.IsNotBlackedOutValidator:
    class: Ginsberg\TransportationBundle\Validator\Constraints\IsNotBlackedOutValidator
    tags:
      - { name: validator.IsNotBlackedOutValidator, alias: blackout }
  
