Ginsberg\TransportationBundle\Entity\Destination:
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 4
          max: 255
Ginsberg\TransportationBundle\Entity\Reservation:
  properties:
    start:
      - NotBlank: ~
      - Ginsberg\TransportationBundle\Validator\Constraints\IsNotBlackedOut: ~
    end:
      - NotBlank: ~
      - Ginsberg\TransportationBundle\Validator\Constraints\IsNotBlackedOut: ~
    destination: 
      - NotBlank: { groups: [pc] }
    destinationText: 
      - NotBlank: { groups: [nonpc] }
Ginsberg\TransportationBundle\Entity\Person:
  properties:
    phone:
      - NotBlank: { groups: [registration] }
      - Length: { min: 10, max: 18, groups: [registration] }
    isTermsAgreed:
      - 'True': { groups: [registration] }