security:
  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
    ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
  providers:
    userprovider:
      id: user_provider
    in_memory:
        memory: 
          users:
            admin: { password: admin, roles: 'ROLE_ADMIN' }
            super: { password: admin, roles: 'ROLE_SUPER_ADMIN' }

  firewalls:
    dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false
    secured_area:
      pattern: ^/
      anonymous: ~
      form_login:
        login_path: login
        check_path: login_check
        default_target_path: reservation

    default:
          anonymous: ~
  access_control:
    - { path: ^/installation, roles: ROLE_SUPER_ADMIN }
    
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    Ginsberg\TransportationBundle\Security\User\User: plaintext
