<?php

namespace Ginsberg\TransportationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstallationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstallationRepository extends EntityRepository
{
  /**
   * Validation rule for blackout start and end dates.
   * Ensures that dates are properly interpreted.
   * Dates in 1969 are not valid.
   */
	public function date_is_valid($attribute, $params)
	{
	  $value = date('Y-m-d H:i:s', strtotime($this->$attribute));
	  if( substr($value, 0, 4) === '1969'):
	    $this->addError($attribute,yii::t($attribute,'Sorry, we didn\'t understand the date you entered.'));
	    $this->$attribute = '';
	  endif;
	}
}
