<?php

namespace Ginsberg\TransportationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProgramRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramRepository extends EntityRepository
{
  /**
  * Get Program name based on official name of the program's MCommunity eligibility group.
  */
  public static function get_program_name_by_ldap_group($ldap_group) 
  {
    $repository = $this->getDoctrine()->getRepository('GinsbergTransportationBundle:Program');
    $program = $repository->findBy($ldap_group);
    if ($program) {
      return $program->getName();
    } else {
      return false;
    }
  }

  /**
  * Get Program Id based on official name of the program's MCommunity eligibility group.
  */
  public static function get_program_id_by_ldap_group($ldap_group) 
  {
    $repository = $this->getDoctrine()->getRepository('GinsbergTransportationBundle:Program');
    $program = $repository->findBy($ldap_group);
    if ($program) {
      return $program->getId();
    } else {
      return false;
    }
  }
}
