<?php

namespace Ginsberg\TransportationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VehicleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleRepository extends EntityRepository
{
  public function findAllSorted()
  {
    $dql = 'SELECT v FROM GinsbergTransportationBundle:Vehicle v ORDER BY v.isActive DESC, v.program ASC';
    $query = $this->getEntityManager()->createQuery($dql);

    try {
      return $query->getResult();
    } catch (\Doctrine\ORM\NoResultException $ex) {
      return null;
    }
  }
  
  public function findActiveVehiclesByProgram($reservation)
  {
    $dql = 'SELECT v FROM GinsbergTransportationBundle:Vehicle v WHERE 
            v.isActive = 1 AND v.program = :program AND v.capacity >= :capacity ORDER BY v.capacity ASC';
    $query = $this->getEntityManager()->createQuery($dql)->setParameters(array(':program' => $reservation->getProgram(), ':capacity' => $reservation->getSeatsRequired()));

    try {
      return $query->getResult();
    } catch (\Doctrine\ORM\NoResultException $ex) {
      return null;
    }
  }
  
  
  
  public function findActiveVehiclesByCapacity($reservation)
  {
    $dql = 'SELECT v FROM GinsbergTransportationBundle:Vehicle v WHERE 
            v.isActive = 1 AND v.capacity >= :capacity ORDER BY v.capacity ASC';
    $query = $this->getEntityManager()->createQuery($dql)->setParameters(array(':capacity' => $reservation->getSeatsRequired()));

    try {
      return $query->getResult();
    } catch (\Doctrine\ORM\NoResultException $ex) {
      return null;
    }
  }
}
