Ginsberg\TransportationBundle\Entity\Installation:
    type: entity
    repositoryClass: Ginsberg\TransportationBundle\Entity\InstallationRepository
    table: installation
    id:
        id:
            type: integer
            generator:
              strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
            nullable: false
        isOpen:
            type: boolean
            nullable: true
        reservationsOpen:
            type: string
            length: 255
            nullable: true
        carsAvailable:
          type: string
          length: 255
          nullable: true
        fallStart:
          type: datetime
          nullable: true
        thanksgivingStart:
          type: datetime
          nullable: true
        thanksgivingEnd:
          type: datetime
          nullable: true
        fallEnd:
          type: datetime
          nullable: true
        winterStart:
          type: datetime
          nullable: true
        mlkStart:
          type: datetime
          nullable: true
        mlkEnd:
          type: datetime
          nullable: true
        springbreakStart:
          type: datetime
          nullable: true
        springbreakEnd:
          type: datetime
          nullable: true
        winterEnd:
          type: datetime
          nullable: true
        fallBack:
          type: datetime
          nullable: true
        springForward:
          type: datetime
          nullable: true
        dailyOpen:
          type: string
          length: 12
          nullable: true
        dailyClose:
          type: string
          length: 12
          nullable: true
    