Ginsberg\TransportationBundle\Entity\Person:
    type: entity
    repositoryClass: Ginsberg\TransportationBundle\Entity\PersonRepository
    table: person
    id:
        id:
            type: integer
            generator:
              strategy: AUTO
    fields:
        first_name:
            type: string
            length: 100
        last_name:
            type: string
            length: 100
        uniqname:
            type: string
            length: 25
            unique: true
        phone:
          type: string
          length: 20
        status:
          type: string
          length: 100
          nullable: true
        date_approved:
          type: datetime
          nullable: true
        is_terms_agreed:
          type: boolean
          nullable: true
        is_ticket_unpaid:
          type: boolean
          nullable: true
        created:
          type: datetime
        modified:
          type: datetime
          nullable: true
    oneToMany:
      reservations:
            targetEntity: Reservation
            mappedBy: person
    manyToOne:
      program:
            targetEntity: Program
            inversedBy: persons
            joinColumn:
                name: program_id
                referencedColumnName: id
                nullable: false
    lifeCycleCallbacks: [ setModifiedValue, setCreatedValue ]
