Ginsberg\TransportationBundle\Entity\Person:
    type: entity
    repositoryClass: Ginsberg\TransportationBundle\Entity\PersonRepository
    table: person
    id:
        id:
            type: integer
            generator:
              strategy: AUTO
    fields:
        firstName:
            type: string
            length: 100
        lastName:
            type: string
            length: 100
        uniqname:
            type: string
            length: 25
            unique: true
        phone:
          type: string
          length: 20
          nullable: true
        status:
          type: string
          length: 100
          nullable: true
        dateApproved:
          type: datetime
          nullable: true
        isTermsAgreed:
          type: boolean
          nullable: true
        hasUnpaidTicket:
          type: boolean
          nullable: true
        created:
          type: datetime
        modified:
          type: datetime
          nullable: true
    oneToMany:
      reservations:
            targetEntity: Reservation
            mappedBy: person
    manyToOne:
      program:
            targetEntity: Program
            inversedBy: persons
            joinColumn:
                name: program_id
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: 
      prePersist: [ setCreatedValue ]
      preUpdate: [ setModifiedValue ]
