Ginsberg\TransportationBundle\Entity\Program:
    type: entity
    table: program
    id:
        id:
            type: integer
            generator:
              strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
            nullable: false
        shortcode:
            type: integer
            nullable: false
        eligibility_group:
            type: string
            length: 255
            nullable: false
    oneToMany:
        destinations:
            targetEntity: Destination
            mappedBy: program
    oneToMany:
        persons:
            targetEntity: Person
            mappedBy: program
    oneToMany:
        vehicles:
            targetEntity: Vehicle
            mappedBy: program
    oneToMany:
        reservations:
            targetEntity: Reservation
            mappedBy: program
