Ginsberg\TransportationBundle\Entity\Reservation:
    type: entity
    repositoryClass: Ginsberg\TransportationBundle\Entity\ReservationRepository
    table: reservation
    id:
        id:
            type: integer
            generator:
              strategy: AUTO
    fields:
        start:
          type: datetime
        end:
          type: datetime
        checkout:
          type: datetime
          nullable: true
        checkin:
          type: datetime
          nullable: true
        created:
          type: datetime
        modified:
          type: datetime
          nullable: true
        seats_required:
          type: smallint
        destination_text:
          type: string
          length: 100
          nullable: true
        notes:
          type: string
          length: 255
          nullable: true
        is_noshow:
          type: boolean
          nullable: true
    oneToMany:
      tickets:
            targetEntity: Ticket
            mappedBy: reservation
    manyToOne:
      program:
            targetEntity: Program
            inversedBy: reservations
            joinColumn:
                name: program_id
                referencedColumnName: id
                nullable: false
      vehicle:
            targetEntity: Vehicle
            inversedBy: reservations
            joinColumn:
                name: vehicle_id
                referencedColumnName: id
                nullable: true
      series:
            targetEntity: Series
            inversedBy: reservations
            joinColumn:
                name: series_id
                referencedColumnName: id
                nullable: true
      destination:
            targetEntity: Destination
            inversedBy: reservations
            joinColumn:
                name: destination_id
                referencedColumnName: id
                nullable: true
      person:
            targetEntity: Person
            inversedBy: reservations
            joinColumn:
                name: person_id
                referencedColumnName: id
                nullable: false